format_version: 2
environments:
  pre-qa:
    pipelines:
      - configuration
pipelines:
  configuration:
    group: node-js-pipeline
    lock_behavior: unlockWhenFinished
    materials:
      nodejs:
        git: https://github.com/stellawi/gocd-file-configuration.git
    stages:
      - build:
          fetch_materials: true
          keep_artifacts: true
          clean_workspace: true
          jobs:
            verification:
              resources:
                - local-agent
              tasks:
                - exec:
                    run_if: passed
                    command: bash
                    arguments:
                    - -cl
                    - echo ${GO_PIPELINE_LABEL} > gocd-file-configuration-label.txt
              artifacts:
                - build:
                    source: "*"
                    destination: configuration

